contacts/urls.py
from django.conf.urls import patterns, include, url

from rest_framework import routers

import views
from serializers import router
# from views import angular_views


urlpatterns = patterns('',
    # DRF API viewer
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/v0.1/', include(router.urls)),

    # Angular app
    url(r'^$', 'contacts.views.angular_view'),

    # Misc Actions
    url(r'^staff/facility_change/(?P<facility_name>.*)/$','contacts.views.staff_facility_change'), #If we have more than 9 facilities we'd need to change this
    url(r'^staff/date/(?P<direction>back|forward)/(?P<delta>\d{1,365})/$','contacts.views.change_current_date'),
    url(r'^staff/change_password/','contacts.views.change_password',name='mx-change-password'),

    # crispy-form partial
    url(r'^crispy-forms/participant/new/?$','contacts.views.crispy.participant_add'),
    url(r'^crispy-forms/participant/update/?$','contacts.views.crispy.participant_update'),

    # static archive site
    url(r'^static_archive/?$', 'contacts.views.static_archive_index'),
    url(r'^static_archive/participants/(?P<study_id>\d{4})(.html)?$', 'contacts.views.static_archive_participant'),

)

mwach/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
import contacts.urls as contacts_urls
from transports import http, africas_talking

urlpatterns = [
    # Main Angular Index and Rest API
    url(r'^', include(contacts_urls)),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', auth_views.login, {'template_name': 'login.html'}),
    url(r'^accounts/logout/$', auth_views.logout),
    url(r'^message_test/',include(http.urls)),
    url(r'^africas_talking/',include(africas_talking.urls)),
]

contacts/models/contact.py
#!/usr/bin/python
# Python Imports
from hashlib import sha256
import collections
import datetime, numbers

# Django Imports
from django.conf import settings
from django.db import models

# Local Imports
from contacts.models import PhoneCall, Practitioner, Visit, Connection
from utils import enums
from utils.models import TimeStampedModel, ForUserQuerySet
import backend.models as back
import utils
import transports


class ContactQuerySet(ForUserQuerySet):

    participant_field = None

    def get_from_phone_number(self,phone_number):
        try:
            return Connection.objects.get(identity=phone_number).contact
        except Connection.DoesNotExist as e:
            raise Contact.DoesNotExist()

    def annotate_messages(self):

        return self.annotate(
            msg_outgoing=utils.sql_count_when(message__is_outgoing=True),
            msg_system=utils.sql_count_when(message__is_system=True),
            msg_nurse=utils.sql_count_when(~models.Q(message__translation_status='cust'),
            message__is_system=False,message__is_outgoing=True),
            msg_incoming=utils.sql_count_when(message__is_outgoing=False),
            msg_delivered=utils.sql_count_when(message__external_status='Success'),
            msg_sent=utils.sql_count_when(message__external_status='Sent'),
            msg_failed=utils.sql_count_when(message__external_status='Failed'),
        ).annotate(
            msg_missed=models.F('msg_outgoing') - models.F('msg_delivered'),
            msg_other=models.F('msg_outgoing') - models.F('msg_delivered') - models.F('msg_sent'),
            # sim_count=models.Count('connection',distinct=True),
        )

    def send_batch(self,english,swahili=None,luo=None,auto='',send=False,control=False):
        """ Send a message to all participants in the query set
            english: required text
            swahili, luo: optional translated text
            auto: string to tag in the auto link field, will prefix with custom.
            send: boolean flag to send messages (default false)
            control: boolean flag to send messages to control group (default false)
        """

        if swahili is None:
            swahili = english
        if luo is None:
            luo = english
        text_translations = {'english':english,'swahili':swahili,'luo':luo}

        original_count = self.count()
        send_to = self.active_users()
        send_count = send_to.count()
        print "Sending to {} of {}".format(send_count,original_count)

        counts = collections.Counter()
        for p in send_to.all():
            # Send the correct language message to all participants
            text = text_translations.get(p.language,english)
            text = text.format( **p.message_kwargs() )

            if send is True:
                msg = p.send_message(
                    text=text,
                    translation_status='cust',
                    auto='custom.{}'.format(auto) if auto != '' else 'custom',
                    translated_text= english if p.language != english else '',
                    control=control,
                    is_system=False,
                )
                counts[msg.external_status] += 1
            else:
                print "({}) -- {}".format(p , text[:40])

        if send is True:
            print "Send Status:\n", "\n\t".join( "{} -> {}".format(key,count) for key,count in counts.most_common() )

        return send_count


class ContactManager(models.Manager):

    def get_queryset(self):
        qs = super(ContactManager,self).get_queryset()
        return qs.annotate(
            note_count=models.Count('note',distinct=True),
            phonecall_count=models.Count('phonecall',distinct=True),
        ).prefetch_related('connection_set',
            models.Prefetch(
                'visit_set',
                queryset=Visit.objects.order_by('scheduled').filter(arrived__isnull=True,status='pending'),
                to_attr='pending_visits'
            )
        )


class Contact(TimeStampedModel):

    STATUS_CHOICES = (
        ('pregnant','Pregnant'),
        ('over','Post-Date'),
        ('post','Post-Partum'),
        ('ccc','CCC'),
        ('completed','Completed'),
        ('stopped','Withdrew'),
        ('loss','SAE opt-in'),
        ('sae','SAE opt-out'),
        ('other','Admin Stop'),
        ('quit','Left Study'),
    )

    NO_SMS_STATUS = ForUserQuerySet.NO_SMS_STATUS
    NOT_ACTIVE_STATUS = ForUserQuerySet.NOT_ACTIVE_STATUS

    LANGUAGE_CHOICES = (
        ('english','English'),
        ('luo','Luo'),
        ('swahili','Swahili'),
    )

    CONDITION_CHOICES = (
        ('art','1 - Starting ART'),
        ('adolescent','2 - Adolescent'),
        ('first','3 - First Time Mother'),
        ('normal','4 -  Normal'),
        ('multiple','5 - Twins'),
    )

    FAMILY_PLANNING_CHOICES = (
        ('none','None'),
        ('iud','IUD'),
        ('pill','Pills'),
        ('depot','Depot'),
        ('implant','Implant'),

    )

    RELATIONSHIP_CHOICES = (
        ('single','Single'),
        ('partner','Partner'),
        ('married','Married'),
        ('seperated','Seperated'),
    )

    DAY_CHOICES = (
        (0,'Monday'),
        (1,'Tuesday'),
        (2,'Wednesday'),
        (3,'Thursday'),
        (4,'Friday'),
        (5,'Satuday'),
        (6,'Sunday'),
    )

    TIME_CHOICES = (
        (8,'Morning (8 AM)'),
        (13,'Afternoon (1 PM)'),
        (20,'Evening (8 PM)'),
    )

    MESSAGING_CHOICES = (
        ('none','No HIV Messaging'),
        ('initiated','HIV Content If Initiated'),
        ('system','HIV Content Allowed'),
    )

    DELIVERY_SOURCE_CHOICES = (
        ('phone','Phone'),
        ('sms','SMS'),
        ('visit','Clinic Visit'),
        ('m2m',"Mothers to Mothers"),
        ('other','Other'),
    )

    #Set Custom Manager
    objects = ContactManager.from_queryset(ContactQuerySet)()
    objects_no_link = ContactQuerySet.as_manager()

    #Study Attributes
    study_id = models.CharField(max_length=10,unique=True,verbose_name='Study ID',help_text="* Use Barcode Scanner")
    anc_num = models.CharField(max_length=15,verbose_name='ANC #')
    ccc_num = models.CharField(max_length=15,verbose_name='CCC #',blank=True,null=True)
    facility = models.CharField(max_length=15,choices=settings.FACILITY_CHOICES)

    study_group = models.CharField(max_length=10,choices=enums.GROUP_CHOICES,verbose_name='Group')
    send_day = models.IntegerField(choices=DAY_CHOICES, default=0,verbose_name='Send Day')
    send_time = models.IntegerField(choices=TIME_CHOICES,default=8,verbose_name='Send Time')

    # Required Client Personal Information
    nickname = models.CharField(max_length=20)
    birthdate = models.DateField(verbose_name='DOB')

    # Optional Clinet Personal Informaiton
    partner_name = models.CharField(max_length=40,blank=True,verbose_name='Partner Name')
    relationship_status = models.CharField(max_length=15,choices=RELATIONSHIP_CHOICES,verbose_name='Relationship Status',blank=True)
    previous_pregnancies = models.IntegerField(blank=True,null=True,help_text='* excluding current')
    phone_shared = models.NullBooleanField(verbose_name='Phone Shared')

    # Required Medical Information
    status = models.CharField(max_length=15,choices=STATUS_CHOICES, default='pregnant')
    language = models.CharField(max_length=10,choices=LANGUAGE_CHOICES,default='english')
    condition = models.CharField(max_length=15,choices=CONDITION_CHOICES,default='normal')
    due_date = models.DateField(verbose_name='Estimated Delivery Date')

    delivery_date = models.DateField(verbose_name='Delivery Date',blank=True,null=True)
    delivery_source = models.CharField(max_length=10,verbose_name="Delivery Notification Source",choices=DELIVERY_SOURCE_CHOICES,blank=True)

    # Optional Medical Informaton
    art_initiation = models.DateField(blank=True,null=True,help_text='Date of ART Initiation',verbose_name='ART Initiation')
    hiv_disclosed = models.NullBooleanField(blank=True,verbose_name='HIV Disclosed')
    hiv_messaging = models.CharField(max_length=15,choices=MESSAGING_CHOICES,default='none',verbose_name='HIV Messaging')
    child_hiv_status = models.NullBooleanField(blank=True,verbose_name='Child HIV Status')
    family_planning = models.CharField(max_length=10,blank=True,choices=FAMILY_PLANNING_CHOICES,verbose_name='Family Planning')
    loss_date = models.DateField(blank=True,null=True,help_text='SAE date if applicable')
    second_preg = models.BooleanField(blank=True,choices=enums.BOOL_CHOICES,verbose_name='Second Pregnancy',default=False)

    #State attributes to be edited by the system
    last_msg_client = models.DateField(blank=True,null=True,help_text='Date of last client message received',editable=False)
    last_msg_system = models.DateField(blank=True,null=True,help_text='Date of last system message sent',editable=False)
    is_validated = models.BooleanField(default=False,blank=True)
    validation_key = models.CharField(max_length=5,blank=True)

    class Meta:
        app_label = 'contacts'

    def __init__(self, *args, **kwargs):
        ''' Override __init__ to save old status'''
        super(Contact,self).__init__(*args,**kwargs)
        self._old_status = self.status
        self._old_hiv_messaging = self.hiv_messaging

    def save(self, force_insert=False, force_update=False, *args, **kwargs):
        # Check that self.id exists so this is not the first save
        if not self._old_status == self.status and self.id is not None:
            self.statuschange_set.create(old=self._old_status,new=self.status,comment='Status Admin Change')

        if not self._old_hiv_messaging == self.hiv_messaging and self.id is not None:
            print self._old_hiv_messaging, self.hiv_messaging
            self.statuschange_set.create(old=self._old_hiv_messaging,new=self.hiv_messaging,
                comment='HIV messaging changed',type='hiv')

contacts/models/message.py
#!/usr/bin/python
#Django Imports
from django.db import models
from django.db.models import Q
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist

from constance import config

#Local Imports
from utils.models import TimeStampedModel, BaseQuerySet

class MessageQuerySet(BaseQuerySet):

    def pending(self):
        return self.filter(is_viewed=False,is_outgoing=False)

    def to_translate(self):
        return self.filter(is_system=False,translation_status='todo')

    def for_user(self,user):
        try:
            return self.filter(contact__facility=user.practitioner.facility)
        except (ObjectDoesNotExist, AttributeError) as e:
            return self.none()

    def top(self):
        return self[:2]


class Message(TimeStampedModel):

    #Set Custom Manager
    objects = MessageQuerySet.as_manager()

    STATUS_CHOICES = (
        ('todo','Todo'),
        ('none','None'),
        ('done','Done')
    )

    class Meta:
        ordering = ('-created',)
        app_label = 'contacts'

    text = models.CharField(max_length=1000,help_text='Text of the SMS message')

    #Boolean Flags on Message
    is_outgoing = models.BooleanField(default=True)
    is_system = models.BooleanField(default=True)
    is_viewed = models.BooleanField(default=False)
    is_related = models.NullBooleanField(default=None,blank=True,null=True)

    # ToDo:Link To Automated Message
    parent = models.ForeignKey('contacts.Message',related_name='replies',blank=True,null=True)

    # translation
    translated_text = models.CharField(max_length=1000,help_text='Text of the translated message',default=None,blank=True,null=True)
    translation_status = models.CharField(max_length='5',help_text='Status of translation',choices=STATUS_CHOICES,default='todo')

    # Meta Data
    languages = models.CharField(max_length=100,help_text='Semi colon seperated list of languages',default=None,blank=True,null=True)
    topic = models.CharField(max_length=50,help_text='The topic of this message',default='',blank=True)

    admin_user = models.ForeignKey(settings.MESSAGING_ADMIN, blank=True, null=True)
    connection = models.ForeignKey(settings.MESSAGING_CONNECTION)
    contact = models.ForeignKey(settings.MESSAGING_CONTACT,blank=True,null=True)

    #Africa's Talking Data
    #ToDo: make this a data field once we know the format
    time_received = models.CharField(max_length=50,default=None,blank=True,null=True)
    external_id = models.CharField(max_length=50,default=None,blank=True,null=True)
    external_linkId = models.CharField(max_length=50,default=None,blank=True,null=True)

    def is_translated(self):
        return self.translation_status == 'done'

    def translation_skipped(self):
        return self.translation_status == 'none'

    def is_translation_pending(self):
        return (not self.is_translated) and (not self.is_system)

    def is_pending(self):
        return not self.is_viewed and not self.is_outgoing

    def sent_by(self):
        if self.is_outgoing:
            if self.is_system:
                return 'system'
            return 'nurse'
        return 'participant'

    def study_id(self):
        if self.contact:
            return self.contact.study_id
        return None
    study_id.short_description = 'Study ID'
    study_id.admin_order_field = 'contact__study_id'

    def contact_name(self):
        if self.contact:
            return str(self.contact.nickname)
        return None
    contact_name.short_description = 'Contact Name'
    contact_name.admin_order_field = 'contact__nickname'

    def identity(self):
        return self.connection.identity
    identity.short_description = 'Identity'
    identity.admin_order_field = 'connection__identity'

    def weeks(self):
        return self.contact.weeks(today=self.created.date())

    def is_pregnant(self):
        return self.contact.was_pregnant(today=self.created.date())

    def dismiss(self,is_related=None,topic='',**kwargs):
		if is_related is not None:
			self.is_related = is_related
		if topic != '':
			self.topic = topic
		self.is_viewed = True
		self.save()

    @staticmethod
    def receive(number,message,time_received,external_id,external_linkId):
        '''
        Main hook for receiving messages
            * number: the phone number of the incoming message
            * message: the text of the incoming message
        '''
        from contacts.models import Connection
        #Get incoming connection
        connection,created = Connection.objects.get_or_create(identity=number)
        contact = None if created else connection.contact
        Message.objects.create(
            is_system=False,
            is_outgoing=False,
            text=message,
            connection=connection,
            contact=contact,
            time_received=time_received,
            external_id=external_id,
            external_linkId=external_linkId
        )

    @staticmethod
    def send(contact,message,translation,is_translated=False,translate_skipped=False,is_system=True,parent=None,languages=None,**kwargs):

        if config.AFRICAS_TALKING_SEND:
            import africas_talking
            try:
                at_id = africas_talking.send(contact.connection.identity,message)
            except africas_talking.AfricasTalkingException as e:
                at_id = 'error'

        _msg = Message.objects.create(
            is_system=is_system,
            text=message,
            translated_text=translation,
            is_translated=is_translated,
            translate_skipped=translate_skipped,
            connection=contact.connection,
            contact=contact,
            is_viewed=True,
            parent=parent,
            external_id=at_id
        )

        if languages:
            lang_objs = Language.objects.filter(id__in=languages)
            _msg.languages = lang_objs
            _msg.save()

contacts/templates/static_archive/index.html
<html>

 <head>
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
 <link rel="stylesheet" href="{{static_dir}}styles.css"/>

 <script>

function gotoID() {
  var study_id = document.querySelector("#study-id").value;
  if (study_id.match(/\d{4}/) == null) {
    console.log("Invalid ID. Must be four digit number");
    return;
  }
  window.location.assign("participants/"+study_id+".html#messages");
}
</script>
 </head>

<body>

<header>
  <h1 class="display-3 text-center"> Static mWaChX Files</h1>
  <div class="text-center">
    <span class="h4">Study ID: </span>
    <input onkeydown="if (event.keyCode == 13) gotoID()" id="study-id" class="mx-2" type="number"/>
    <button onclick="gotoID()">Go</button>
  </div>
</header>

<div id="table-holder">
  <table class="table table-striped table-hover">
    <tr>
      <th>ID
      <th>Nickname
      <th>Study Group
      <th>Facility
      <th>Enrolled
    {% for participant in participants %}
      <a href=>
      <tr onclick="window.location.assign('participants/{{participant.study_id}}.html#messages')">
        <td>{{participant.study_id}}
        <td>{{participant.nickname}}
        <td>{{participant.study_group|title}}
        <td>{{participant.facility|title}}
        <td>{{participant.created|date:'M d, Y'}}
    {% endfor %}
  </table>
</div>

contacts/templates/static_archive/participant.html
{% load tz %}
<html>

 <head>
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
 <link rel="stylesheet" href="{{static_dir}}styles.css"/>
 <script src="{{static_dir}}script.js"></script>
</head>

<body>

<header>
  <span><a href="../">&#8612; Back</a></span>
  <h1> <p class="text-center p-3"> {{ p.study_id }} -- {{ p.nickname }} -- {{ p.study_group|title}} -- {{ p.facility|title }}</p></h1>
  <ul id="menu-bar"></ul>
</header>

<div id="tab-holder">

  <section id="messages" class="tab visible">
    {% for msg in p.message_set.all %}
    <div class="item msg {{msg.sent_by}}">
      <h4>{{msg.sent_by}} <small class="text-mutted">{{msg.created}}</small></h4>
      <div class="content original">
        {{ msg.text }}
      </div>
      <div class="content translation visible">
        {% if msg.translated_text.strip %}
          {{ msg.translated_text }}
        {% else %}
          {{ msg.text }}
        {% endif %}
      </div>
    </div>
    {% endfor %}
  </section>

  <section id="visits" class="tab">
    {% for visit in p.visit_set.all %}
    <div class="item visit">
      <h4>{{visit.visit_type}} <small class="text-mutted">{{visit.status}}</small> </h4>
          <b>Scheduled: </b>{{ visit.scheduled }}
          {% if visit.arrived %}
          <b>Attended: </b>{{ visit.arrived }}
          {% endif %}
    </div>
    {% endfor %}
  </section>

  <section id="calls" class="tab">
    {% for call in p.phonecall_set.all %}
    <div class="item visit">
      <h4>{% if call.is_outgoing %} Nurse {% else %} Participant {% endif %} -- {{call.outcome}}
        <small class="text-mutted">{{call.created|date:'M d, Y H:i'}}</small></h4>
      <div class="content">
        {{call.comment}}
      </div>
    </div>
    {% endfor %}
  </section>

  <section id="notes" class="tab">
    {% for note in p.note_set.all %}
    <div class="item visit">
      <h4>{{note.created}}</h1>
      <div class="content">
        {{note.comment}}
      </div>
    </div>
    {% endfor %}
  </section>

  <section id="status-updates" class="tab">
    {% for update in p.statuschange_set.all %}
      <div class="item update">
        <h4>{{update.type}} <small class="text-mutted">{{update.created|date:'M d, Y'}}</small></h4>
        {{update.old}} &#8594; {{update.new}}
      </div>
    {% endfor %}
  </section>

</div>

<div id="participant-info">
  <ul>
    <li id="translate-sms" class="d-none" ><h1>Show Original SMS:</h1><input name="toggle-translate" type="checkbox"/></li>
    <li><h1>Language:</h1>{{p.get_language_display}}</li>
    <li><h1>Enrolled:</h1><span>{{p.created|date:'M d, Y'}}</li>
    <li><h1>Status:</h1><span>{{p.get_status_display}}</li>
    <li><h1>Group:</h1><span>{{p.get_study_group_display}}</li>
    <li><h1>Site:</h1>{{p.get_facility_display}}</li>
    <li><h1>Due Date:</h1><span>{{p.due_date}}</li>
    {% if not p.is_pregnant %}
    <li><h1>Delivery Date:</h1><span>{{p.delivery_date}}</li>
    {% endif %}
    {% if p.loss_date %}
    <li><h1>Loss Date:</h1><span>{{p.loss_date}}</li>
    {% endif %}
    <li><h1>Age:</h1><span>{{p.age_signup}}</li>
    <li><h1>Condition:</h1>{{p.get_condition_display}}</li>
    <li><h1>Previous Pregnancies:</h1>{{p.previous_pregnancies}}</li>
    <li><h1>Second Pregnancy:</h1>{{p.second_preg}}</li>
    <li><h1>Phone Shared:</h1>{{p.phone_shared}}</li>
    <li><h1><u>Counts and Stats</u></h1></li>
    <li><h1>Participant:</h1><span>{{p.msg_incoming}}</li>
    <li><h1>System:</h1><span>{{p.msg_system}}</li>
    <li><h1>Nurse:</h1><span>{{p.msg_nurse}}</li>
    <li><h1>Visits:</h1><span>{{p.visit_set.count}}</li>
    <li><h1>Calls:</h1><span>{{p.phonecall_set.count}}</li>
    <li><h1>Notes:</h1><span>{{p.note_set.count}}</li>
  </ul>
</div>

</body>

</html>